library-updater:
  image: miniwaveme/library-updater
  working_dir: /usr/src/app
  volumes:
    - ./:/usr/src/app
    - ./test:/usr/src/music #TODO FORMALIZE THIS BETTER
  links:
    - database

database:
  image: mongo:3.2
  command: mongod --smallfiles --quiet --logpath=/dev/null
  volumes:
    - ./data/db:/data/db
  ports:
    - "27017:27017"